### ISSUE TITLE
making restart after result

### ISSUE THREAD

**Issue by Biniben** [Mohammad-Farmaan/JavaScript-Calculator#26]
when calculating one full/ needed calculation then when u start another calculation by clicking a number It has to start over means it has to act as "clicking 'C' i.e. '0' and adding the number as new one"

**Comment by zxcodes** [comment]
If you have a valid issue, create a PR and attach it with a Video or Screenshot.

**Comment by Biniben** [comment]
How can I do that?

**Comment by zxcodes** [comment]
Make the appropriate changes in the code that you are suggesting and then create a Pull Request.
reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
