### ISSUE TITLE
Floating Point Precision Problem

### ISSUE THREAD

**Issue by ZigaoWang** [Mohammad-Farmaan/JavaScript-Calculator#33]
There is the common problem of math in JS environment: the floating point precision problem.
Example: 0.1+0.2=0.30000000000000004
As a calculator web app, I think this problem is very serious and need to be fixed ASAP.
Thank you!

**Comment by islommamarajapov** [comment]
hello

**Comment by islommamarajapov** [comment]
My name is Islom

**Comment by islommamarajapov** [comment]
I am from Uzbekistan

**Comment by ZigaoWang** [comment]
I from China, what's up?

**Comment by ZigaoWang** [comment]
This issue is fixed in this pull request: https://github.com/zxcodes/Calculator/pull/36
