### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by ghost** [Mohammad-Farmaan/JavaScript-Calculator#6]
Bro I just started started web development. And i have also created calculator please watch :- https://harsh-koli.github.io/calc

**Comment by Harsh-Koli** [comment]
A Simple Calculator

**Comment by zxcodes** [comment]
That's great. You need to focus on the UI so it can be even better.

**Comment by ghost** [comment]
Hmm yes, because i have just started naa. That's way i can't visualize it
properly.

**Comment by zxcodes** [comment]
Yeah, no issues. You'll get there.
