### ISSUE TITLE
Undefined when clicking "=" button.

### ISSUE THREAD

**Issue by rajeevcodes0** [Mohammad-Farmaan/JavaScript-Calculator#7]
It shows "undefined" to the screen if we press the "=" button without entering anything, which i guess , is not the expected behavior.

![firefox_dVgYvsPNtE](https://user-images.githubusercontent.com/96406474/152997652-f2a33e49-1c4d-4a9a-a881-805fcb2575af.png)

**Comment by DeepanshuGoel1122** [comment]
It's now solved... Previously when we press = and then we do some calculations, it writes digits after undefined word.. means undefined word didn't go.. [ undefined 1+2 ] like this.. that's the issue which has been already resolved..

**Comment by zxcodes** [comment]
Thanks for reporting @rajeevcodes0. The issue has been fixed.
